<a href="https://colab.research.google.com/github/vikasverma9721/Expert-Python-Programming/blob/main/Tensor_Using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Import Library***

In [ ]:
import torch

### ***Check Version***

In [ ]:
## check version
print(torch.__version__)

2.10.0+cpu


### ***Creating a Tensor***

In [ ]:
## using empty
a = torch.empty(2,3)

In [ ]:
a

tensor([[2.0809e-18, 4.5094e-41, 2.0811e-18],
        [4.5094e-41, 2.0810e-18, 4.5094e-41]])

In [ ]:
# Check datatype
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(5,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# using rand
torch.rand(3,3)

tensor([[0.5955, 0.9204, 0.6702],
        [0.1388, 0.3302, 0.9374],
        [0.8785, 0.8086, 0.1101]])

In [ ]:
# manual_seed
torch.manual_seed(10)
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [ ]:
## Using tensor
torch.tensor([[0,1,2,3],[4,5,6,7]])

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [ ]:
x = torch.tensor([[2,3,4,6],[4,5,2,1]])
x

tensor([[2, 3, 4, 6],
        [4, 5, 2, 1]])

In [ ]:
# check shape
x.shape

torch.Size([2, 4])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068654568117382454, 3473746696326492210,
         6498751669754409774],
        [7309453675965983778, 8315168162784306286, 8367752027310484831,
         7954801838398993778]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10,7)

tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])

In [ ]:
# manual seed
torch.manual_seed(10)
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
x = torch.tensor([[7,2,3],[4,5,6]])
print(x)

tensor([[7, 2, 3],
        [4, 5, 6]])


In [ ]:
x.shape

torch.Size([2, 3])

### ***Tensor Data Types***

In [ ]:
# find data type formate : "name of tensor.dtype"
x.dtype

torch.int64

In [ ]:
# assign data type (changes the data type from one to another or can say
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[7., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.full((5,3), 2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## ***Mathematical operations***

#### ***1. Scalar operation***

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2139, 0.4118],
        [0.6938, 0.9693]])

In [ ]:
a =x + 2  # Addition

b = x - 2  # Subtraction

c = x * 2  # Multiply

d = x / 2  # Division

e = (x * 100)//2  # int division

f = ((x ** 100)//3)%2  #modulous

g = x ** 2  #power

In [ ]:
print("ADD = ",a)
print("SUB = ",b)
c
d
e
f
g

tensor([[0.3817, 0.1091, 0.3002],
        [0.1971, 0.4957, 0.3105]])

### ***Element wise operation***

In [ ]:
x = torch.rand(2,3)
y = torch.rand(2,3)

print(x)
print(y)

tensor([[0.6178, 0.3304, 0.5479],
        [0.4440, 0.7041, 0.5573]])
tensor([[0.6959, 0.9849, 0.2924],
        [0.4823, 0.6150, 0.4967]])


In [ ]:
x + y  #add

x - y  #sub

x * y  #mul

x / y  #divi

x ** y  #power

x % y  #mod

tensor([[0.6178, 0.3304, 0.2556],
        [0.4440, 0.0891, 0.0605]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

- He needs to remove the minus sign of ABS.

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

- The function of negative is that it changes negative into positive and positive into negative.

In [ ]:
z = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(z)

tensor([2., 2., 4., 4.])

- Rounding converts floating-point numbers (decimal numbers) within the tensor to their nearest integer. This is commonly referred to as rounding off.

In [ ]:
# ciel
torch.ceil(z)

tensor([2., 3., 4., 5.])

- Its function is to round floating-point (decimal) numbers within the tensor to their next largest integer.

In [ ]:
# floor
torch.floor(z)

tensor([1., 2., 3., 4.])

- This does the exact opposite of torch.ceil(). Its job is to round floating-point (decimal) numbers within the tensor to their nearest integer (integer) value.

In [ ]:
# clamp
torch.clamp(z, min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

- Clamp's job is to place a boundary (limit) on the numbers within the tensor. This is also known as "clip" or "capping" in simple language.

### ***Reduction Operation***

In [ ]:
a = torch.randint(size=(2,3),low = 0, high = 10, dtype = torch.float32)
a

tensor([[8., 2., 6.],
        [6., 4., 4.]])

In [ ]:
torch.sum(a, dim = 0)

tensor([13.,  3.,  8.])

In [ ]:
torch.sum(a)

tensor(24.)

In [ ]:
# mean
torch.mean(a)

#mean along columns
torch.mean(e, dim = 0)

tensor([26.0000, 25.5000, 27.0000])

In [ ]:
# median
torch.median(a)

tensor(4.)

- Logic: Averages the entire tensor.

In [ ]:
#max and min
torch.max(a)
torch.min(a)

tensor(0.)

- Logic: Scans the entire tensor as a single list.It doesn't discriminate between rows/columns, extracts the highest or lowest value from the entire matrix and returns a single number (scalar).

In [ ]:
# product
torch.prod(a)

tensor(17010.)

- Multiplies all the elements of the entire tensor together.

In [ ]:
#standard deviation
torch.std(a)

tensor(2.9944)

- Finds the standard deviation (spread) of the entire tensor at once.
This shows how dispersed the data is across the matrix.

In [ ]:
# variance
torch.var(a)

tensor(8.9667)

- Finds the variance (spread) of the entire tensor at once. The average of each element is the square of the gap between them.

In [ ]:
# argmax
torch.argmax(a)

tensor(0)

- Views the entire matrix as a single flat line (1st list) and returns the index position (starting at 0) of the largest number.

In [ ]:
# argmin
torch.argmin(a)

tensor(1)

- Views the entire matrix as a single flat line (1st list) and returns the index position (starting at 0) of the smallest number.

### ***Matrix Operations***

In [ ]:
d = torch.randint(size = (2,3), low = 0, high = 10)
e = torch.randint(size = (3,2), low = 0, high = 10)

print(d)
print(e)

tensor([[4, 3, 0],
        [4, 3, 1]])
tensor([[4, 2],
        [3, 1],
        [5, 4]])


In [ ]:
# matrix multiplacation
torch.matmul(d, e)

tensor([[25, 11],
        [30, 15]])

- The logic of matrix multiplication is similar to standard math—"Dot Product of Rows and Columns" (i.e. multiplying the horizontal row of the first matrix by the vertical column of the second matrix).

In [ ]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(32)

- It multiplies the opposite numbers of two equally sized vectors (1D tensors) together, and then adds the answers together. Ultimately, you get a single number.

In [ ]:
# transpose
torch.transpose(d,0,1)

tensor([[4, 4],
        [3, 3],
        [0, 1]])

- This function flips the matrix diagonally (corners). Data that was previously horizontal in rows is now vertical in columns.

In [ ]:
b = torch.randint(size=(3,3), low = 0, high = 10, dtype = torch.float32)
b

tensor([[2., 3., 0.],
        [8., 4., 7.],
        [6., 5., 6.]])

In [ ]:
# determinant
torch.det(b)

tensor(-40.0000)

- It converts any square matrix (e.g. 2x2, 3x3) into a single number (scalar) by solving it according to mathematical rules.

In [ ]:
#inverse
torch.inverse(b)

tensor([[ 0.2750,  0.4500, -0.5250],
        [ 0.1500, -0.3000,  0.3500],
        [-0.4000, -0.2000,  0.4000]])

### ***Comparison Oepration***

In [ ]:
a = torch.randint(size = (2,3), low = 0, high = 10)
b = torch.randint(size = (2,3), low = 0, high = 10)

print(a)
print(b)

tensor([[9, 6, 1],
        [1, 0, 5]])
tensor([[5, 2, 5],
        [6, 0, 1]])


In [ ]:
print("Greater Than (a > b):")
print(a > b)
print("--" * 30)

print("Less Than (a < b):")
print(a < b)
print("--" * 30)

print("Equal To (a == b):")
print(a == b)
print("--" * 30)

print("Not Equal To (a != b):")
print(a != b)
print("--" * 30)

print("Greater Than Equal To (a >= b):")
print(a >= b)
print("--" * 30)

print("Less Than Equal To (a <= b):")
print(a <= b)

Greater Than (a > b):
tensor([[ True,  True, False],
        [False, False,  True]])
------------------------------------------------------------
Less Than (a < b):
tensor([[False, False,  True],
        [ True, False, False]])
------------------------------------------------------------
Equal To (a == b):
tensor([[False, False, False],
        [False,  True, False]])
------------------------------------------------------------
Not Equal To (a != b):
tensor([[ True,  True,  True],
        [ True, False,  True]])
------------------------------------------------------------
Greater Than Equal To (a >= b):
tensor([[ True,  True, False],
        [False,  True,  True]])
------------------------------------------------------------
Less Than Equal To (a <= b):
tensor([[False, False,  True],
        [ True,  True, False]])


### ***Special Functions***

In [ ]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[2., 4., 7.],
        [4., 6., 1.]])

In [ ]:
# log
torch.log(k)

tensor([[0.6931, 1.3863, 1.9459],
        [1.3863, 1.7918, 0.0000]])

In [ ]:
# exp
torch.exp(k)

tensor([[   7.3891,   54.5981, 1096.6332],
        [  54.5981,  403.4288,    2.7183]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 2.0000, 2.6458],
        [2.0000, 2.4495, 1.0000]])

In [ ]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(k)

tensor([[0.8808, 0.9820, 0.9991],
        [0.9820, 0.9975, 0.7311]])

In [ ]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(k, dim=1)

tensor([[0.0064, 0.0471, 0.9465],
        [0.1185, 0.8756, 0.0059]])

### ***Inplace Operations***

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0070, 0.1550, 0.1167],
        [0.7467, 0.8735, 0.6535]])
tensor([[0.8925, 0.8363, 0.8716],
        [0.6402, 0.7507, 0.9861]])


In [ ]:
m.add_(n)

tensor([[0.8996, 0.9913, 0.9883],
        [1.3869, 1.6242, 1.6396]])

In [ ]:
m

tensor([[0.8996, 0.9913, 0.9883],
        [1.3869, 1.6242, 1.6396]])

In [ ]:
n

tensor([[0.8925, 0.8363, 0.8716],
        [0.6402, 0.7507, 0.9861]])

In [ ]:
torch.relu(m)

tensor([[0.8996, 0.9913, 0.9883],
        [1.3869, 1.6242, 1.6396]])

In [ ]:
m

tensor([[0.8996, 0.9913, 0.9883],
        [1.3869, 1.6242, 1.6396]])

### ***Capying a Tensor***

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.6095, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
b = x

In [ ]:
b

tensor([[0.6095, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
x[0][0] = 0

In [ ]:
x

tensor([[0.0000, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
b

tensor([[0.0000, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
id(x)

140357680722112

In [ ]:
id(b)

140357680722112

In [ ]:
b = x.clone()

In [ ]:
x

tensor([[0.0000, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
b

tensor([[0.0000, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
x[0][0] = 10

In [ ]:
x

tensor([[10.0000,  0.7046,  0.4193],
        [ 0.8443,  0.2048,  0.5378]])

In [ ]:
b

tensor([[0.0000, 0.7046, 0.4193],
        [0.8443, 0.2048, 0.5378]])

In [ ]:
id(x)

140357680722112

In [ ]:
id(b)

140356693358576

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
z = torch.empty_like(a)

In [ ]:
z

tensor([[              4970,                  0, 822472613547737088],
        [                 0,                  0,           11206656]])