<a href="https://colab.research.google.com/github/vikasverma9721/Expert-Python-Programming/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Check version

In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
tf.__version__

'2.20.0'

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x = tf.constant(10.5)
x

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [ ]:
y = tf.constant("Hello World")
y

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [ ]:
b = tf.constant([1,2,3,4,5,6])
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

### Import Numpy library

In [ ]:
import numpy as np

#### Create 2d Array using Numpy

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
tf.constant

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
t_2d = tf.constant([[4,5], [6,7]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

#### 1D Array

In [ ]:
t_1d = tf.constant([1,2,3,4,5])
t_1d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
x = tf.constant([5,2,6,4,3,2,1])
x

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([5, 2, 6, 4, 3, 2, 1], dtype=int32)>

In [ ]:
t_2d_1 = tf.constant([1,2,3,4],shape = (2,2), dtype = "int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### 3D

In [ ]:
t_3d_1 = tf.constant([[[1,2],[3,4],[5,6]]],dtype = "float32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>

In [ ]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t_3d_1.shape

TensorShape([1, 3, 2])

## Tensorflow Variable

In [ ]:
# Variable constructor requires an initial value for the variable
# which can be a tensor of any type & shape.
# This initial value defines the type & shape of the variable.
# After construction the type & shape of the variable are fixed.

In [ ]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.name

'Variable:0'

In [ ]:
x.shape

TensorShape([4])

In [ ]:
x.dtype

tf.int32

In [ ]:
y = tf.Variable([1.0,2,3.3,4])
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [ ]:
z = tf.Variable(True,False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

## Create Tensorflow variable with different Shape

In [ ]:
t_2d = tf.Variable([[1,2,3],[4,5,6]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
#Get index of highest value
t_2d

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.argmax(t_2d)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [ ]:
# Viewed/Convert as a Tensor

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# Change/Assign New Value to Tensor

In [ ]:
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.assign([10,20,30,40])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
x.assign([4,6,2,9])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
# Assign addition Variable with another Memory

In [ ]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

## Tensorflow Math Modules

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a = 10
b = 20

In [ ]:
a+b

30

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# Addition of Two List

In [ ]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
# Addition of Two tuple
t1 = (2,3,4,5)
t2 = (5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [ ]:
l1 = [1,2,3,4]
a = 10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# Given a tensor x and tensorr y, this operation x^y computes for corresponding elements in x and y

In [ ]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# tf.math.abs

# real number
x = tf.constant([-2.25,3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [ ]:
# tf.math.subtract
x = [1,2,3,4,5]
y = 1
tf.subtract(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [ ]:
x = [1,2,3,4,5]
y = 1
tf.subtract(y,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [ ]:
# tf.math.multiply
x = tf.constant(([1,2,3,4]))
tf.math.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
x = tf.ones([1,2]);
y = tf.ones([2,1]);
x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# tf.math.maximum
x = tf.constant([0.,0.,0.,0.])
y = tf.constant([-2,0.,2.,5.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
x = tf.constant([-5,0.,0.,0.])
y = tf.constant([-3.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [ ]:
# tf.math.minimum
x = tf.constant([0.,0.,0.,0.])
y = tf.constant([-5.,-2.,0.,3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [ ]:
x = tf.constant([-5.,0.,0.,0.])
y = tf.constant(-3.)
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [ ]:
# tf.math.log
x = tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [ ]:
# tf.math.divide
x = tf.constant([10,20,30])
y = tf.constant([2,3,4])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([5.        , 6.66666667, 7.5       ])>

In [ ]:
# tf.math.pow
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# tf.math.sqrt
x = tf.constant([[4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
y = tf.constant([[-4.0],[16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [ ]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [ ]:
ones_2d = tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [ ]:
ones_3d = tf.ones((2,2,3),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [ ]:
# ones_like:Creates a tensor of all ones that has the same shape as the input.
tensor = tf.constant([[1,2,3],[4,5,6]])
tf.ones_like(tensor)

In [ ]:
tensor = tf.constant([[1,2,3],[4,5,6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>